### Get all alerts

GET http://{{host}}:{{port}}/alerts

### filter alerts

GET http://{{host}}:{{port}}/alerts?is_open=false&tag=java&creator_id=1

### Get all tags

GET http://{{host}}:{{port}}/tags

### Create new alert

POST http://{{host}}:{{port}}/alerts
Content-Type: application/json

{
  "creator_id": 1,
  "title": "Hello, world",
  "description": "Lorem ipsum",
  "tag": "java",
  "priority": 0
}

### Assign alert

PATCH http://{{host}}:{{port}}/alerts/2457dd72-430b-4e79-9672-780ac874470f
Content-Type: application/json
Accept: application/json

{
  "assignee_id": 2,
  "id": "2457dd72-430b-4e79-9672-780ac874470f"
}

###