### Get all alerts

GET http://{{host}}:{{port}}/alerts

### filter alerts

GET http://{{host}}:{{port}}/alerts?is_open=true&tag=golang&user_id=1

### Get all tags

GET http://{{host}}:{{port}}/tags

### Create new alert

POST http://{{host}}:{{port}}/alerts
Content-Type: application/json

{
  "user_id": 1,
  "title": "Hello, world",
  "description": "Lorem ipsum",
  "tag": "java",
  "priority": 0
}

### Assign alert

PATCH http://{{host}}:{{port}}/alerts/22883ca9-2779-47be-aed4-10ccbe119b9c
Content-Type: application/json

{
  "assignee_id": 2,
  "id": "22883ca9-2779-47be-aed4-10ccbe119b9c"
}

###